// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoneroBot.Database;

#nullable disable

namespace MoneroBot.Database.Migrations
{
    [DbContext(typeof(MoneroBotContext))]
    [Migration("20220514051243_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("MoneroBot.Database.Models.Bounty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PostNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("SubAddressIndex")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "PostNumber" }, "PostsHaveASingleBounty");

                    b.HasIndex(new[] { "SubAddressIndex" }, "SubAddressIndexesCannotBeReused");

                    b.HasIndex(new[] { "SubAddress" }, "SubAddressesCannotBeReused");

                    b.ToTable("Bounties");
                });

            modelBuilder.Entity("MoneroBot.Database.Models.BountyContribution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BountyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CommentId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Confirmations")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BountyId");

                    b.ToTable("BountyContributions");
                });

            modelBuilder.Entity("MoneroBot.Database.Models.BountyContribution", b =>
                {
                    b.HasOne("MoneroBot.Database.Models.Bounty", "Bounty")
                        .WithMany("Contributions")
                        .HasForeignKey("BountyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bounty");
                });

            modelBuilder.Entity("MoneroBot.Database.Models.Bounty", b =>
                {
                    b.Navigation("Contributions");
                });
#pragma warning restore 612, 618
        }
    }
}
