// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoneroBot.Database;

#nullable disable

namespace MoneroBot.Database.Migrations
{
    [DbContext(typeof(MoneroBotContext))]
    partial class MoneroBotContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("MoneroBot.Database.Entities.Bounty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("AccountIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CommentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PostNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("SubAddressIndex")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "PostNumber" }, "PostsHaveASingleBounty");

                    b.HasIndex(new[] { "SubAddressIndex" }, "SubAddressIndexesCannotBeReused");

                    b.HasIndex(new[] { "SubAddress" }, "SubAddressesCannotBeReused");

                    b.ToTable("Bounties");
                });

            modelBuilder.Entity("MoneroBot.Database.Entities.BountyContribution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BountyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CommentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BountyId");

                    b.HasIndex("TransactionId");

                    b.ToTable("BountyContributions");
                });

            modelBuilder.Entity("MoneroBot.Database.Entities.QueryResults.PostNumber", b =>
                {
                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.ToTable("PostNumber", null, t => t.ExcludeFromMigrations());
                });

            modelBuilder.Entity("MoneroBot.Database.Entities.XmrTransaction", b =>
                {
                    b.Property<string>("TransactionId")
                        .HasColumnType("TEXT");

                    b.Property<uint>("AccountIndex")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("BlockHeight")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSpent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsUnlocked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("SubAddressIndex")
                        .HasColumnType("INTEGER");

                    b.HasKey("TransactionId");

                    b.ToTable("XmrTransactions");
                });

            modelBuilder.Entity("MoneroBot.Database.Entities.BountyContribution", b =>
                {
                    b.HasOne("MoneroBot.Database.Entities.Bounty", "Bounty")
                        .WithMany("Contributions")
                        .HasForeignKey("BountyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MoneroBot.Database.Entities.XmrTransaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bounty");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("MoneroBot.Database.Entities.Bounty", b =>
                {
                    b.Navigation("Contributions");
                });
#pragma warning restore 612, 618
        }
    }
}
